import Head from "next/head";
import Footer from "../components/Footer";
import HeroSlider from "../components/HeroSlider";
import SellingProducts from "../components/SellingProducts";
export default function Home() {
  return (
    <>
      <Head>
        <title>Phonix E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSlider />
      <SellingProducts />
      <div className="products-container">product dislplay</div>
      <Footer/>
    </>
  );
}
