import Head from "next/head";
import DisplayProducts from "../components/DisplayProducts";
import Footer from "../components/Footer";
import HeroSlider from "../components/HeroSlider";
import SellingProducts from "../components/SellingProducts";
import { client } from "../lib/client";


export default function Home({ products, bannerData }) {
  return (
    <>
      <Head>
        <title>Phonix E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSlider bannerInfo={bannerData[0]} />
      <SellingProducts />
      <DisplayProducts allProducts={products} />
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const products = await client.fetch(`*[_type == "product"]`);
  const bannerData = await client.fetch(`*[_type == "banner"]`);

  return {
    props: {
      products,
      bannerData,
    },
  };
}
